### ISSUE TITLE
Execution time is not display in slack notification

### ISSUE THREAD

**Issue by karlloic** [8398a7/action-slack#103]
I used custom_payload to send notifications to slack but the **execution time** with ${process.env.AS_TOOK} is not displayed.

Here is what my step looks like

```yaml
- name: Slack notification
  uses: 8398a7/action-slack@v3
  with:
    status: custom
    fields: workflow,job,commit,repo,ref,author,took
    custom_payload: |
      {
        attachments: [{
          color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
          text: `${process.env.AS_WORKFLOW}\n$Build (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} completed with ${{ job.status }} in ${process.env.AS_TOOK}`,
        }]
      }
  env:
    GITHUB_TOKEN: ${{ github.token }}
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  if: always()
```

And the resulting slack message

![image](https://user-images.githubusercontent.com/8680885/89749954-ebd8eb00-da97-11ea-9d72-43abc9868663.png)
