### ISSUE TITLE
“Job is not found. Check the matrix.”

### ISSUE THREAD

**Issue by mkarlesky** [8398a7/action-slack#108]
**Describe the bug**
About two weeks ago the job field of our Github Action reports in Slack changed to report “Job is not found. Check the matrix.” The Action configuration has not changed in that time. To our knowledge nothing related to the Github Action or our git workflow or team activity has changed.

**Expected behavior**
The expected behavior is the Slack message produced by the action to include the job name from the Githhub action configuration.

**Screenshots**
Here is a sample report in Slack before the behavior changed.
<img width="663" alt="Screen Shot 2020-09-03 at 12 04 40 PM" src="https://user-images.githubusercontent.com/1048550/92139949-7b936000-edde-11ea-8413-fdb52a3d82ad.png">

Here is a sample report in Slack after the behavior changed:
<img width="665" alt="Screen Shot 2020-09-03 at 12 04 12 PM" src="https://user-images.githubusercontent.com/1048550/92139947-7afac980-edde-11ea-969d-04a5dd13870b.png">

**Additional context**
Here is the config from our Github Action configuration:

```
- uses: 8398a7/action-slack@v3
  with:
    icon_emoji: ':octocat:'
    status: ${{ job.status }}
    fields: repo,author,eventName,workflow,job
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK }}
  if: always() # Pick up events even if the job fails or is canceled.

```

**Comment by jaroldwong** [comment]
Have you tried adding the `MATRIX_CONTEXT`? https://action-slack.netlify.app/fields

**Comment by 8398a7** [comment]
@mkarlesky 
@jaroldwong  comments are spot on.

**Comment by jgrossmac** [comment]
How does something like `${process.env.AS_TOOK}` work with a job matrix?

**Comment by 8398a7** [comment]
@jgrossmac I didn't see the relevance of this issue.
There is also a lack of information, so please follow the template and put up another issue.

**Comment by mkarlesky** [comment]
@8398a7 @jaroldwong Thank you for the prompt help. We have not tried this, no. I'm not clear from the documentation how this helps (though I certainly believe you). Could either of you explain how `MATRIX_CONTEXT` applies here and what the correct value should be given our configuration? Thank you again.

**Comment by 8398a7** [comment]
The document clearly states that it is necessary.
Please tell me what you don't understand about the documentation.

https://action-slack.netlify.app/fields
![image](https://user-images.githubusercontent.com/8043276/92478324-f6b0a800-f21c-11ea-9332-90941f8644d6.png)

**Comment by mkarlesky** [comment]
My apologies for not being clearer. I see that it is required. I was asking what `MATRIX_CONTEXT` accomplishes and how. I was merely hoping to understand what the mechanisms involved are.

> caution: Additional configuration is required to work with matrix.

What is the matrix in this context and what in our configuration causes it to be relevant? Github Actions can be configured as job matrices, but I'm confused how it comes into play here. Our Action configuration specifies two jobs but does not set up a job matrix.

**Comment by 8398a7** [comment]
> MATRIX_CONTEXT: ${{ toJson(matrix) }} # required

Am I understanding that you want to know why this line is necessary?

The reason we need this line is to uniquely identify the job that was executed by matrix.
Currently there is no official ID provided to uniquely identify a job executed by matrix.

Related issue:
- https://github.com/actions/toolkit/issues/550
- https://github.com/actions/runner/issues/324

When this issue is resolved, you no longer need to specify `MATRIX_CONTEXT`.

Realted Code:
- https://github.com/8398a7/action-slack/blob/master/src/client.ts#L65-L74
- https://github.com/8398a7/action-slack/blob/master/src/fields.ts#L113

**Comment by mkarlesky** [comment]
```
      - uses: 8398a7/action-slack@v3
        with:
          icon_emoji: ':octocat:'
          status: ${{ job.status }}
          fields: repo,author,eventName,workflow,job
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}

```

We tried adding `MATRIX_CONTEXT`. Unfortunately, it did not fix the problem. I remain confused why adding `MATRIX_CONTEXT` might have fixed the problem when our Github Action config does not use a job matrix. Our config is just two job listings without any matrix features.

Any other ideas? Thank you for the help.

**Comment by 8398a7** [comment]
If `secrets.GITHUB_TOKEN` is not correct, you may still get this message.
Could you try changing it to the following?

```yaml
  env:
    GITHUB_TOKEN: ${{ github.token }}
```

**Comment by mkarlesky** [comment]
```
     - uses: 8398a7/action-slack@v3
        with:
          icon_emoji: ':octocat:'
          status: ${{ job.status }}
          fields: repo,author,eventName,workflow,job
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: always() # Pick up events even if the job fails or is canceled.
```

The message “Job is not found. Check the matrix.” is still produced in the Slack messages produced by builds with the above configuration.

**Comment by 8398a7** [comment]
This is a template for reporting bug.

> **To Reproduce**
> Please describe the yaml of GitHub Actions that we can reproduce.  
> Please don't write excerpts as the whole setup will affect the behavior.

I believe this reproduction report is written in excerpts. Further investigation is difficult to do from the current state of YAML.
It seems to be affected by settings other than those listed.

**Comment by mkarlesky** [comment]
```
---
# Continuous Integration Workflow: Test case suite run + validation build check
name: CI

# Controls when the action will run.
# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Job: Unit test suite
  unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest

    steps:
      # Install GO environment
      - name: Setup Go environment
        uses: actions/setup-go@v2.0.3
        with:
          # Minimum of 1.14.3 up to but not including 1.15
          go-version: '^1.14.3'

      # Checks out repository under $GITHUB_WORKSPACE
      - name: Checkout Latest Repo
        uses: actions/checkout@v2

      # Set Paths
      - name: Set Path & Environment Variables
        run: |
          echo ::add-path::$GITHUB_WORKSPACE/bin
          echo ::set-env name=GOPATH::$GITHUB_WORKSPACE
          echo ::set-env name=workspace::$GITHUB_WORKSPACE

      # Install Go Tools
      - name: Install Go Tools
        # Mockgen executable
        run: |
          GO111MODULE=on go get github.com/golang/mock/mockgen@v1.4.3

      # Environment Dependencies
      - name: Install SCons
        run: |
          sudo apt-get install -y scons

      # Run Tests
      - name: Run All Unit Tests
        run: |
          scons --directory=$GITHUB_WORKSPACE test:ci

      # Slack notification
      - uses: 8398a7/action-slack@v3
        with:
          icon_emoji: ':octocat:'
          status: ${{ job.status }}
          fields: repo,author,eventName,workflow,job
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: always() # Pick up events even if the job fails or is canceled.

  # Job: Build code as release artifact and run system tests
  build-plus-system-tests:
    name: "Release Build + System Tests"
    runs-on: ubuntu-latest

    steps:
      # Install GO environment
      - name: Setup Go environment
        uses: actions/setup-go@v2.0.3
        with:
          # Minimum of 1.14.3 up to but not including 1.15
          go-version: '^1.14.3'

      # Checks out repository under $GITHUB_WORKSPACE
      - name: Checkout Latest Repo
        uses: actions/checkout@v2

      # Set Paths
      - name: Set Path & Environment Variables
        run: |
          echo ::add-path::$GITHUB_WORKSPACE/bin
          echo ::set-env name=GOPATH::$GITHUB_WORKSPACE
          echo ::set-env name=workspace::$GITHUB_WORKSPACE

      # Install Go Tools
      - name: Install Go Tools
        # Wire executable
        run: |
          GO111MODULE=on go get github.com/google/wire/cmd/wire@v0.4.0

      # Environment Dependencies
      - name: Install SCons
        run: |
          sudo apt-get install -y scons

      # Environment Dependencies
      - name: Install Robot Framework
        run: |
          sudo pip install robotframework==3.2.1

      # Build Release
      - name: Release Build
        run: |
          scons --directory=$GITHUB_WORKSPACE release:all

      # Run System Tests
      - name: Run System Tests
        run: |
          scons --directory=$GITHUB_WORKSPACE robot:all

      # Slack notification
      - uses: 8398a7/action-slack@v3
        with:
          icon_emoji: ':octocat:'
          status: ${{ job.status }}
          fields: repo,author,eventName,workflow,job
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_CHANNEL_WEBHOOK }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: always() # Pick up events even if the job fails or is canceled.

```
