### ISSUE TITLE
AS_MESSAGE is undefined

### ISSUE THREAD

**Issue by kvz** [8398a7/action-slack#112]
**Describe the bug**
Trying to use ${process.env.AS_MESSAGE} in `custom_payload.text` but it just reads as `undefined` in Slack. All other fields work for me.

**To Reproduce**

```yaml
        custom_payload: |
          {
            username: 'action-slack',
            icon_emoji: ':octocat:',
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text: `${process.env.AS_WORKFLOW} of ${process.env.AS_MESSAGE} (${process.env.AS_COMMIT}) in ${process.env.AS_REF.replace('refs/heads/', '')} by ${process.env.AS_AUTHOR.split(/[<@]/)[1]} ${'${{ job.status }}' === 'success' ? 'succeeded' : '${{ job.status }}' === 'failure' ? 'failed' : '${{ job.status }}'} in ${process.env.AS_TOOK}`,
            }]
          }
```

**Expected behavior**
See the first 75 chars of the commit message

**Screenshots**
n/a

**Additional context**
Happy to answer any question, but i hope this is enough to go on :)

**Comment by 8398a7** [comment]
> Please describe the yaml of GitHub Actions that we can reproduce.  
> Please don't write excerpts as the whole setup will affect the behavior.

This reproduction is partial.
I don't have enough information to determine if it's a glitch in the code, so please provide the full text.

**Comment by kvz** [comment]
Thanks for checking this out! I just discovered this was my mistake.

I forgot to add `message` to  the `fields`. It's working now like this:

```yaml
    - uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,job,message,commit,repo,ref,author,took
        custom_payload: |
          {
            username: 'github-action',
            icon_emoji: ':octocat:',
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text: `${process.env.AS_WORKFLOW} of ${process.env.AS_AUTHOR.split(/[<@]/)[1]}'s "${process.env.AS_MESSAGE}" in ${process.env.AS_REF.replace('refs/heads/', '')} ${'${{ job.status }}' === 'success' ? 'succeeded' : '${{ job.status }}' === 'failure' ? 'failed' : '${{ job.status }}'} in ${process.env.AS_TOOK}`,
            }]
          }
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```

:heart: 

Sorry for the noise!

**Comment by 8398a7** [comment]
For custom, it is easier to specify the following

```yaml
    - uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: all # changed
        custom_payload: |
          {
            username: 'github-action',
            icon_emoji: ':octocat:',
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text: `${process.env.AS_WORKFLOW} of ${process.env.AS_AUTHOR.split(/[<@]/)[1]}'s "${process.env.AS_MESSAGE}" in ${process.env.AS_REF.replace('refs/heads/', '')} ${'${{ job.status }}' === 'success' ? 'succeeded' : '${{ job.status }}' === 'failure' ? 'failed' : '${{ job.status }}'} in ${process.env.AS_TOOK}`,
            }]
          }
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```

This is a custom-only recommendation because if you use all outside of custom, you'll even get unnecessary information.
