### ISSUE TITLE
Action is not running today

### ISSUE THREAD

**Issue by zoispag** [8398a7/action-slack#119]
**Describe the bug**
Action is not running today. It should post in Slack. Instead, it throws an error on execution.

**To Reproduce**
Run a workflow with this action

**Expected behavior**
It should post to Slack.

**Screenshots**

![image](https://user-images.githubusercontent.com/21138205/102066860-a2f4c280-3dfa-11eb-8aad-f65cc0ac1cd4.png)

**Additional context**

```yml
      - name: Slack notification
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          fields: repo,message,author,ref,workflow,took
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
```
