### ISSUE TITLE
More consistent version tagging.

### ISSUE THREAD

**Issue by NeilJed** [8398a7/action-slack#123]
All the releases are tagged with the full SEMVER notation (major.minor.patch) which means that when there is a new release dependabot generates a pull request for all of our workflows that use it - and there are a LOT.

Given that SEMVER denotes:
- MAJOR version when you make incompatible API changes,
- MINOR version when you add functionality in a backwards compatible manner, and
- PATCH version when you make backwards compatible bug fixes.

It would be great if you could add major and or major.minor git tags to your release so we can refer to that version in our workflows rather than having to deal with dependabot PRs for every release. Being able to just use @v3 in our workflow would mean the latest compatible branch.

**Comment by 8398a7** [comment]
Isn't what you are looking for satisfied by the following statements?
If what you are looking for is different, it would be great if you could tell us the difference.

```yaml
steps:
  - uses: 8398a7/action-slack@v3
    with:
      status: ${{ job.status }}
      fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
    if: always() # Pick up events even if the job fails or is canceled.
```
