### ISSUE TITLE
Status Code 404

### ISSUE THREAD

**Issue by erin-doyle** [8398a7/action-slack#130]
When I try to use this action I get the following error:
`Error: An HTTP protocol error occurred: statusCode = 404`

Here's what I'm using:
```
- name: Slack Notify
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: message,commit,author,took
          mention: 'Erin'
          if_mention: 'failure,cancelled'
          channel: '#test_channel'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: always()
```

I have set up a WebHook using the Incoming WebHook App in Slack.  I have no idea if I've set things up wrong as there isn't any documentation on how to set up the Slack end of this.
