### ISSUE TITLE
If you are using matrix.include, you will get "Job is not found"

### ISSUE THREAD

**Issue by KoheiKanagu** [8398a7/action-slack#137]
If you use matrix.include, as in the following sample, you will get errors in job and tok.

<img width="518" alt="スクリーンショット 2021-05-06 18 21 39" src="https://user-images.githubusercontent.com/6175794/117274306-e7f7bf00-ae97-11eb-9aec-729c33728869.png">

```yaml
name: Releases
on:
  push:
    branches:
      - master
jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        flavor: [dev, stg, prod]
        include:
          - os: ubuntu-latest
            text: "hello ubuntu"
          - os: macos-latest
            text: "hello macos"

    runs-on: ${{ matrix.os }}
    steps:
      - name: action-slack
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        with:
          fields: repo,commit,job,took,workflow
          status: ${{ job.status }}
          text: "${{ toJson(matrix) }}"
```

In this case, the value of matrix is as follows.
```json
{
 "os": "macos-latest",
 "flavor": "prod",
 "text": "hello macos"
}
```

So, the jobName will be something like `deploy (macos-latest, prod, hello macos)`, and the currentJob will be undefined.
https://github.com/8398a7/action-slack/blob/v3/src/client.ts#L77-L78
https://github.com/8398a7/action-slack/blob/v3/src/fields.ts#L141-L145

If I did not include the matrix.include value in MATRIX_CONTEXT, the job and took worked.
```
MATRIX_CONTEXT: '{"os": "${{ matrix.os }}", "flavor": "${{ matrix.flavor }}" }'
```
