### ISSUE TITLE
send slack notification to multiple channels at once

### ISSUE THREAD

**Issue by sethumadhav07** [8398a7/action-slack#159]
is there a way to send slack notification to multiple channels at once?

```
steps:
  - uses: 8398a7/action-slack@v3
    with:
      channel: '#channel1, #channel2, #channel3'
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
```

when i do the above, i get the below error:
Error: An HTTP protocol error occurred: statusCode = 404
