### ISSUE TITLE
Can do we do use mention with here or channel only, right?

### ISSUE THREAD

**Issue by golfzaptw** [8398a7/action-slack#17]
I want to mention to a user in the channel
```yml
// example.yml
      - name: Notification to slack from QA checking code
        uses: 8398a7/action-slack@v2
        if: success() || failure()
        with:
          status: ${{ job.status }}
          author_name: ${{ github.repository }}
          mention: 'golf'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```

**Comment by 8398a7** [comment]
When I check the code, it seems to behave as expected even if I put the username in the mention.
If it works, I'll try to fix the documentation but didn't work?

**Comment by golfzaptw** [comment]
@8398a7 Yes, If I used it send message to slack. It shows `<!golf>`

**Comment by 8398a7** [comment]
I see.

Looking at the documentation, it seems that you need to use `@`.
https://api.slack.com/reference/surfaces/formatting#mentioning-users

I want to add a key called user_mention so that I can write as follows.

```yaml
      - name: Notification to slack from QA checking code
        uses: 8398a7/action-slack@v2
        if: success() || failure()
        with:
          status: ${{ job.status }}
          author_name: ${{ github.repository }}
          user_mention: 'XXXXX'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```

What you have provided is the username specification, which seems to be a deprecated notation.
`Hey <@U024BE7LH>, thanks for submitting your report.`
I think that `golf` will work for the time being, but also consider the method recommended by slack.
