### ISSUE TITLE
"Job is not found" message appearing in job and took fields

### ISSUE THREAD

**Issue by phr3nzii** [8398a7/action-slack#185]
**Describe the bug**
When trying to output the job name and time taken in a Slack message I am getting a "Job is not found" message. However, if I overwrite the job name then the details are successfully populated.

**To Reproduce**
This is the GitHub Actions config that I have used:
```
name: Slack Test Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  slack_test:
    name: Slack Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Hello
        run: echo "Hello!"
      - name: Slack Notification
        uses: 8398a7/action-slack@v3.13.0
        with:
          status: ${{ job.status }}
          fields: repo,job,commit,workflow,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
```

If you add
```
job_name: Slack Test Job
```
to the `with` section then the `job` and `took` fields are populated correctly on the Slack message.

**Expected behavior**
My understanding is that the job name should automatically be detected, which would then mean that the `job` and `took` fields are successfully populated. If that is correct then I would expect those fields to be successfully populated without having to specify the job name.

**Screenshots**
![image](https://user-images.githubusercontent.com/909911/149535608-3ebfbca6-92c2-4dc5-afa0-bbf62bb1c38f.png)
