### ISSUE TITLE
Is it possible to pass parameters in the text field?

### ISSUE THREAD

**Issue by bennymeade** [8398a7/action-slack#199]
Set a job env var: ` QA_ENV_URL: myprivateurl`

```
- name: Slack notification with repo links
        if: always()
        uses: 8398a7/action-slack@v3.13.0
        with:
          status: ${{ job.status }}
          fields: message,author,eventName,workflow
          icon_emoji: ':speaker:'
          text: 'Company repo: ${GITHUB_REF##*/} :construction_worker:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TEST_AUTOMATION_QA }}
```
This example prints the full line as a string.
![image](https://user-images.githubusercontent.com/1033474/154843592-028c5874-d3b0-48cd-a8be-708fdad7c0b6.png)

Is it possible to pass parameters in the text field?
