### ISSUE TITLE
Can you solve the problem in the following ways?

### ISSUE THREAD

**Issue by fran38** [8398a7/action-slack#231]
Can you solve the problem in the following ways?

```yaml
steps:
  - uses: 8398a7/action-slack@v3
    with:
      fields: repo,commit,action
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
```

I'll consider adding it to the list because of the lack of documentation.

_Originally posted by @8398a7 in https://github.com/8398a7/action-slack/issues/66#issuecomment-639996321_
