### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by kdemon1011** [8398a7/action-slack#239]
Hi
I am using V3.15.1 and getting the following error. We have the GitHub Enterprise version.
`Error: Resource not accessible by integration`

and this is the configuration

```
   with:
    github_base_url: https://github.com/data-sentinel-ai
    status: success
    fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
    author_name: 8398a7@action-slack
    github_token: ***
  env:
    SLACK_WEBHOOK_URL: ***
```

Can you help us to resolve the issue? Thanks

**Comment by vijaybaliah** [comment]
> Hi I am using V3.15.1 and getting the following error. We have the GitHub Enterprise version. `Error: Resource not accessible by integration`
> 
> and this is the configuration
> 
> ```
>  - uses: 8398a7/action-slack@v3.15.1
>         with:
>           github_base_url: https://github.com/data-sentinel-ai
>           status: ${{ job.status }}
>           fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
>         env:
>           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
>         if: always() # Pick up events even if the job fails or is canceled.
> ```
> 
> Can you help us to resolve the issue? Thanks

got this same error when using GitHub Enterprise version

**Comment by maersu** [comment]
Got it working for our enterprise with `permissions` in `jobs` and `github_base_url` in `with` (see [README](https://github.com/8398a7/action-slack#for-github-enterprise) on the buttom)

```
jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v3
      - uses: 8398a7/action-slack@v3
        with:
          github_base_url: https://github.com/enterprises/gobugfree
          status: custom
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
          custom_payload: |
          .........
```

**Comment by saintevil** [comment]
To fix and resolve:

Go to the effected GitHub repository to where the error is happening
Select Settings -> Actions -> General
Change to read and write permissions

but free plan not supported

https://thomasthornton.cloud/2024/01/31/github-action-error-resource-not-accessible-by-integration-when-attempting-to-upload-sarif-report-files-to-github/

**Comment by younsl** [comment]
Here's my solution. 

The following error occurred in the `action-slack` step.

```bash
Error: Resource not accessible by integration
```

As mentioned in the [README](https://github.com/8398a7/action-slack?tab=readme-ov-file#require-permissions), you additionally grant `actions: read` permission to actions workflow file using the `permissions` keyword.

```yaml
# .github/workflows/release.yml
permissions:
  contents: read
  actions: read
  
jobs:
  main-job:
    # ... omitted for brevity ...
    
  notification:
    runs-on: [self-hosted, linux]
    needs: [main-job]
    steps:
    - name: Slack Notification
      uses: 8398a7/action-slack@v3
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: custom
        fields: repo,commit,message,author,action,eventName,ref,workflow,job,took
        custom_payload: |
          # ... omitted for brevity ...
```

Even without write permission in Workflow permissions section in repository settings, it works well just by granting `actions: read` to actions workflow file.

<img width="772" alt="image" src="https://github.com/user-attachments/assets/f4f65c99-0957-49b2-9a29-cbdbb4cc76fc" />
