### ISSUE TITLE
GLIBC not found

### ISSUE THREAD

**Issue by jgengo** [8398a7/action-slack#252]
**Describe the bug**

My projects running `8398a7/action-slack` are failing for the following reason:

> /opt/actions-runner/externals/node20/bin/node: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /opt/actions-runner/externals/node20/bin/node)
> /opt/actions-runner/externals/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /opt/actions-runner/externals/node20/bin/node)
> /opt/actions-runner/externals/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /opt/actions-runner/externals/node20/bin/node)

All the workflow is successful and should then just send a notification on Slack.

**To Reproduce**

Here is my workflow.yml

```yaml
  notify:
    name: Slack notification
    needs: deploy
    if: always()
    runs-on: self-hosted

    steps:
    - uses: technote-space/workflow-conclusion-action@v3
    - uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,commit,repo,ref,author,message
        custom_payload: |
          {
            username: "GitHub Actions",
            icon_emoji: ":github:",
            attachments: [{
              color: '${{ env.WORKFLOW_CONCLUSION }}' === 'success' ? 'good' : '${{ env.WORKFLOW_CONCLUSION }}' === 'failure' ? 'danger' : 'warning',
              text: `${process.env.AS_WORKFLOW}: ${{ env.WORKFLOW_CONCLUSION }} on ${process.env.AS_REPO}\n(${process.env.AS_COMMIT}): ${process.env.AS_MESSAGE}\nCommited by ${process.env.AS_AUTHOR}`,
            }]
          }
      env:
        GITHUB_TOKEN: ${{ secrets.YOUR_GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
```
