### ISSUE TITLE
Channel configuration broken?

### ISSUE THREAD

**Issue by Hurtak** [8398a7/action-slack#253]
**Describe the bug**
The channel property seems to not work, it always sends the message to default channel. I tried putting there channel id and channel name (both with and without #) and with the same result - the job succeeds but the message gets sent to default channel

This is our CI  step

```yaml
  send_slack_notification:
    needs: check_company
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send to Slack
        uses: 8398a7/action-slack@v3
        with:
          channel: "CHANNEL_ID"
          status: "${{ needs.check_company.result }}"
          text: "e2e daily tests status: ${{ needs.check_company.result }}"
          fields: workflowRun
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```

Is there some special additional configuration that should be needed?

Also, the documentation seems to conflict itself, one part of the docs says you should put ID, but 2nd part of the docs use the channel name

![Screenshot 2024-02-15 at 10 48 01](https://github.com/8398a7/action-slack/assets/6587821/55e5c309-08c2-457a-8735-aab270ecc527)
![Screenshot 2024-02-15 at 10 48 10](https://github.com/8398a7/action-slack/assets/6587821/6c618526-c2cb-4d6d-8e37-c7625caf4b6c)

Also, shouldn't send to slack job fail in case of incorrectly setup `channel` property? Instead of succeeding and sending to default channel?
