### ISSUE TITLE
(node:2623) [DEP0005] DeprecationWarning: Buffer() is deprecated

### ISSUE THREAD

**Issue by kalanyuz** [8398a7/action-slack#37]
I'm using github actions with
```
    - uses: actions/setup-node@v1.1.0
      name: Installing packages
      with:
        node-version: '10.x'
```
Then I get this error:
```
Run 8398a7/action-slack@v2.6.0
  with:
    status: Success
    author_name: Build & Test
  env:
    GITHUB_TOKEN: ***
    SLACK_WEBHOOK_URL: ***
(node:2623) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
##[error]A request error occurred: connect ECONNREFUSED 127.0.0.1:80
##[error]Node run failed with exit code 1
```
