### ISSUE TITLE
payload conflict

### ISSUE THREAD

**Issue by 8398a7** [8398a7/action-slack#43]
action-slack can specify the `payload` in the with key.

```yaml
- uses: 8398a7/action-slack@v2
  with:
    status: custom
    payload: {}
```

The payload was used only for `status: custom`, but in fact there was a value other than custom.
This seems to be the value that GitHub Actions automatically enters.

Since there are cases where you want to utilize the automatically inserted payload(#38), the action-slack needs to use the custom payload as an alias.
And action-slack needs v3 version to break compatibility.
