### ISSUE TITLE
how to change slack icon for Success?

### ISSUE THREAD

**Issue by rodrigorodriguescosta** [8398a7/action-slack#51]
I'd like to change the icon for success to :heavy_check_mark:  instead of :white_check_mark:, is there any way using parameter to do that?

**Comment by 8398a7** [comment]
There is no easy way to do that up to v2.
This is because a successful message has a fixed part, and its emoji(:white_check_mark:) is a fixed part.
In v3 we will support full overwriting of the body.

It is a little difficult, but if you use the custom type, you can also achieve it with v2.

```yaml
- uses: 8398a7/action-slack@v2
  with:
    status: custom
    payload: |
      {
        text: ':heavy_check_mark: Succeeded',
        attachments: [{
          "author_name": "8398a7@action-slack",
          fallback: 'fallback',
          color: 'good',
          title: 'CI Result',
          text: 'text'
        }]
      }
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
  if: success()
```
