### ISSUE TITLE
Getting link to Github action result web page...

### ISSUE THREAD

**Issue by FonsRademakers** [8398a7/action-slack#66]
Hi, is there a way to get a link to the workflow output webpage?

Thanks. Fons.

**Comment by 8398a7** [comment]
Can you solve the problem in the following ways?

```yaml
steps:
  - uses: 8398a7/action-slack@v3
    with:
      fields: repo,commit,action
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
```

I'll consider adding it to the list because of the lack of documentation.
