### ISSUE TITLE
Setting Job Name in Action

### ISSUE THREAD

**Issue by stack72** [8398a7/action-slack#67]
Hi, 

Firstly, thanks for the work here, it's awesome! 

I wanted to ask about configuring the slack notification to add the name of the action that fails. I originally did the following:

```
      - if: 'failure()'
        name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          text: ${{ job.name }}
          fields: repo,commit,author,action
          status: ${{ job.status }}
```

But that didn't print the test as part of the action. 

Then I tried to override the `author_name` to be `${{ job.name }}` but that hasn't worked either.

This is the final code I am working with right now:

```
      - if: 'failure()'
        name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          author_name: ${{ job.name }}
          fields: repo,commit,author,action
          status: ${{ job.status }}
```

Any help here would be most appreciated

Thanks

Paul
