### ISSUE TITLE
Compact format like travis

### ISSUE THREAD

**Issue by 8398a7** [8398a7/action-slack#70]
> Ok, sad, but if you could add the time the job took and the compact (travis like) formatting I would be very happy.

**Comment by 8398a7** [comment]
@FonsRademakers 

I misunderstood the intent of your comment.
If you want a compact format, such as travis, you can leave the fields unspecified so that only the text you choose to display is shown.

Wouldn't it be more compact if you wrote the following?

```yaml
steps:
  - uses: 8398a7/action-slack@v3
    with:
      status: ${{ job.status }}
      fields: ''
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
```

The job took is not on the agenda here, as we want to discuss it in issue #38.

**Comment by FonsRademakers** [comment]
Hi,

  but only status is not enough, is it? Or do you display all the other information too (action link, hash link, author, duration, message)?

Cheers, Fons.


> On 12 Jun 2020, at 16:28, 839 <notifications@github.com> wrote:
> 
> 
> @FonsRademakers
> 
> I misunderstood the intent of your comment.
> If you want a compact format, such as travis, you can leave the fields unspecified so that only the text you choose to display is shown.
> 
> Wouldn't it be more compact if you wrote the following?
> 
> steps
> :
>   - 
> uses: 8398a7/action-slack@v3
> 
>     
> with
> :
>       
> status: ${{ job.status }}
> 
>       
> fields: ''
> 
>     
> env
> :
>       
> SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
> The job took is not on the agenda here, as we want to discuss it in issue #38.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--------------------------------------------------------------------------
Dr. Fons Rademakers      CERN - European Organization for Nuclear Research
Chief Research Officer   1211 Geneve 23, Switzerland
CERN openlab             Tel: +41227679248            Mobile: +41754113742
--------------------------------------------------------------------------

**Comment by 8398a7** [comment]
Do you think the problem is that the current format makes it too vertical?
Unfortunately, when you commented earlier, the image wasn't showing up on the GitHub Issue.
<img width="747" alt="comment" src="https://user-images.githubusercontent.com/8043276/84560582-67f8d000-ad80-11ea-97ae-fb443b9c3bd6.png">

Do you assume you want to display the following format?

---
Succeeded GitHub Actions
repo: [8398a7/action-slack](https://github.com/8398a7), message: [bump 3.1.0](https://github.com/8398a7/action-slack/commit/631738ba931376027cc461e99e271ac3d33d2fd6), commit: [631738b](https://github.com/8398a7/action-slack/commit/631738ba931376027cc461e99e271ac3d33d2fd6), author: 839<8398a7@gmail.com>, eventName: push, ref: refs/head/master, workflow: [Slack Mainline](https://github.com/8398a7/action-slack/actions/runs/133384245), job: [check_pr](https://github.com/8398a7/action-slack/runs/765625269)

**Comment by FonsRademakers** [comment]
![Screen Shot 2020-06-13 at 17 11 06](https://user-images.githubusercontent.com/2265419/84572220-e9f4f300-ad98-11ea-84f1-2b4e12110146.png)
Hi, hope now the example is clear. Try to be as compact as the Travis CI log message. You could add one last line being the checkin message. You current format is way to vertical. And as in the Travis example only two links are needed (one to the specific action output and one to the specific git hash for the checkin.

**Comment by FonsRademakers** [comment]
Example:
"
Succeeded macOS CI (63edc15) of BioDynaMo/biodynamo@github-actions by Fons Rademakers in 7 min 22 sec
More centos debugging.
"

Where macOS CI is a link to the specific action and where 63edc15 is a link to the pushed code. Having more links or links pointing the same is just confusing.

Thanks, Fons.

**Comment by 8398a7** [comment]
Thank you. Do you use v2 for this?
Explicitly specify the fields (e.g. author, action) to be displayed from v3 is possible.
It is our policy not to support individual user formats, as there is an infinite number of patterns.
It would be better if you can use v3 to focus on the fields you need.

**Comment by FonsRademakers** [comment]
I use v3:

    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: Integration Test
        fields: repo,ref,message,author,action,workflow # default: repo,commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.

which gives this way  to vertical format. Could you not just make one option for a compact format, like:

with:
   fields: compact

or something like that. There are infinite number of patterns, but now there is not a single good one. ;-)

**Comment by 8398a7** [comment]
If a library provides `fields: compact`, it is up to the person to decide what information they want. Doesn't it vary by?

I think it's possible to display them as a comma-separated list instead of using slack attachments.
The message would be as follows.

<img width="1313" alt="ss" src="https://user-images.githubusercontent.com/8043276/84573200-f8173380-add9-11ea-811e-29f6d2fe044f.png">

The values are assumed to be as follows.
Add a `style` key.

```yaml
- name: Notify Slack
  uses: 8398a7/action-slack@v3
  with:
    status: ${{ job.status }}
    author_name: Integration Test
    fields: repo,ref,message,author,action,workflow # default: repo,commit
    style: compact
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
  if: always() # Pick up events even if the job fails or is canceled.
```

By the way, if you restrict the fields like `fields: repo,message`, you can use the I think it will be much more compact.

<img width="493" alt="ss2" src="https://user-images.githubusercontent.com/8043276/84573285-8f7c8680-adda-11ea-9c39-2546a3bf4cb4.png">

**Comment by FonsRademakers** [comment]
I like 'style: compact', but as compact message I would propose:

"Workflow"
"action" ("hash") of "repo"@"branch" by "user" "failed|succeeded|canceled" in "xx" min "yy" sec
"log message"


macOS CI
build (63edc15) of BioDynaMo/biodynamo@bugfix-1 by Fons Rademakers succeeded in 4 min 23 sec
Fix last bug concerning GPU acceleration.

where "workflow", "action", "hash" are links. The log message has an entire line, as message are typically more than 20 chars.

This message is very clear and does not need any redundant keywords to be understandable, like 'repo', 'commit', 'author', 'eventName', 'ref', 'workflow' and 'job'. Everything is clear and concise.

I an my users would be grateful as we get many action Slack message per day.

Cheers, Fons.

**Comment by 8398a7** [comment]
The template itself is great.
But as a library author, I don't want to have to think about the appropriate wording for each additional field.
I'm thinking of taking a break from this and allowing you to specify your preferred template.

```yaml
steps:
  - uses: 8398a7/action-slack@v3
    with:
      status: custom
      custom_payload: |
        {
          text: "${this.workflow()}\n${this.job()} (${this.commit()}) of ${this.repo()}@${this.branch()} by ${this.author()} ${job.status()} in ${took()}\n${message()}",
        }
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
```

This is a big change and it may take some time.
However, I think this feature satisfies two requests: "I don't want to maintain the wording" and "I want to send the formatting I want".
