### ISSUE TITLE
Single notification for workflow

### ISSUE THREAD

**Issue by jasonvarga** [8398a7/action-slack#72]
Is it possible to send a single notification for the entire workflow?

For example, if my workflow has multiple jobs running test suites and all of them fail, my Slack channel gets bombarded with notifications.

If my test suite fails, one notification is enough.

It would be nice for an option for something like "prevent sending if already sent".

**Comment by 8398a7** [comment]
I see. I've certainly felt that too.
I can't think of a very quick way to do it, but I'll try to think of a way.

**Comment by jasonvarga** [comment]
Are there any sort of caches available to the action? (Sorry, don't really know much about Action internals yet)
Perhaps a flag can be stored along with the workflow ID and checked every time it runs?

**Comment by 8398a7** [comment]
Cash is also a good idea.
But state management can be complicated, so I'm thinking of other ideas.

My proposal needs to be narrowed down to the following notation.
The point is twofold.

- A ensures that other jobs will be completed by `with.after_jobs`
- Separate jobs for `action-slack` only

```yaml
name: example
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - run: test
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: lint
  action-slack:
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          after_jobs: test,lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```

In this case, I'd like to do a slack notification after the test and lint jobs are completed.
In GitHub Actions, you can control the order of jobs by `needs`, but this is inappropriate for the requirement because subsequent jobs are skipped when the previous step fails.

We will add a parameter called `after_jobs` to satisfy the requirement.
action-slack monitors the status of the other jobs until the specified job is completed.
Internally you will be monitoring the state of the job by polling, as other job states can be seen in the [Get a job for a workflow run](https://developer.github.com/v3/actions/workflow-jobs/#get-a-job-for-a-workflow-run).

It might be possible to achieve this with a simpler mechanism by separating the workflow, but I haven't given it much thought yet.

**Comment by jfunke-well** [comment]
would including `needs: [test, lint]` on the `action-slack:` be enough? 
https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds

**Comment by 8398a7** [comment]
A specified job must be successful. In this case, no failure notification is given.

**Comment by 8398a7** [comment]
Oops, I was missing out.

```yaml
    needs: [put,other,job,ids,here]
    if: ${{ failure() }}
```

By writing `needs` and `if` together, can I wait until the job is finished and still run the job if it fails?

**Comment by jfunke-well** [comment]
Yes I have it working in my workflow. My testsAll run before this and if any have failed, it will send a slack notification. 
The Needs line specified that this job will wait until the specified jobs are complete, the if statement can be changed to always() if you want it to run every time regardless of the whole workflow success/failure/cancel

**Comment by jfunke-well** [comment]
check out https://github.com/technote-space/workflow-conclusion-action for the best working solution to this

**Comment by jasonvarga** [comment]
The workflow-conclusion-action method worked really well for me. Personally, I'd be fine with just doing that, and not needing anything else added to action-slack.

To clarify, the key seems to be that you can make a separate job that `needs` your other jobs, rather than just another step in an existing job.

```yaml
jobs:
  this-job: ...

  that-job: ...

  slack:
    runs-on: ubuntu-latest
    needs: [this-job, that-job]

    # this is required, otherwise it gets skipped if any needed jobs fail. 
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds
    if: always()

    steps:
      - uses: technote-space/workflow-conclusion-action@v1
      - name: Send Slack notification
        uses: 8398a7/action-slack@v2
        if: env.WORKFLOW_CONCLUSION == 'failure'
        with:
          status: failure
          author_name: ${{ github.actor }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Thanks @8398a7 and @jfunke-well !
