### ISSUE TITLE
Breaking change in minor a update?

### ISSUE THREAD

**Issue by Veetaha** [8398a7/action-slack#87]
Why a [breaking change](https://github.com/8398a7/action-slack/releases/tag/v3.2.0) was introduced in a minor update? This is very surprising, I was using the `action` field API but now it suddenly stopped working without me touching the major version of this action.
Minor versions should **always** be compatible with lower **minor** versions within the same major release.
Please refer to the [semver spec item no 7](https://semver.org/#spec-item-7). If you are not following the semver protocol, please state so explicitly in the docs.

**Comment by 8398a7** [comment]
I'm sorry. There's no excuse for this.
I put it in because the notification doesn't fail, but I'd like to put the `action` back in v3.

**Comment by Veetaha** [comment]
Thanks, I was already looking for an alternative for `the action` field, not that it is still present in the `README.md` example.

**Comment by 8398a7** [comment]
The reason for this was that the roles of action and workflow are very similar.
I think workflow is a higher level feature, so I would recommend it if you want to replace it.

**Comment by Veetaha** [comment]
Well I'd like to get the link to the specific run of the workflow where the message to slack was sent, if I am not mistaken `workflow` field only gives the link to the latest run of the workflow which, but browsing the history of messages in the slack I'd like to have the link not to the latest workflow run, but to the run where the message was sent

**Comment by 8398a7** [comment]
The link between action and workflow is the same, except the field name and display name have been changed.

action
https://github.com/8398a7/action-slack/blob/v3.1.0/src/client.ts#L226
workflow
https://github.com/8398a7/action-slack/blob/v3.4.0/src/fields.ts#L169

The feature you are looking for may be the newly added job field.
https://action-slack.netlify.app/fields

**Comment by Veetaha** [comment]
Aha, thanks for the pointer and for the patch!

**Comment by Veetaha** [comment]
@8398a7 hmm, are you sure that `job` field works?
I got this message:
![image](https://user-images.githubusercontent.com/36276403/86256752-5c4f3b00-bbc1-11ea-88a0-e71e456838bb.png)
with a link  `https://github.com/owner/repo/runs/undefined` 
with the following config:
```yaml
name: Send failure message to Slack
    uses: 8398a7/action-slack@v3
    with:
      status: failure
      fields: job,author
      text: "Testing failure message to PR. Hello world!."
      author_name: ""
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```
Note that there is no author field in the message either.

**Comment by 8398a7** [comment]
Are you using matrix?
It's a known issue that it is undefined in that case.

refs: #86

**Comment by 8398a7** [comment]
Oh, you need to specify GITHUB_TOKEN if you want to use a job.

```yaml
    uses: 8398a7/action-slack@v3
    with:
      status: failure
      fields: job,author
      text: "Testing failure message to PR. Hello world!."
      author_name: ""
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```

refs: https://action-slack.netlify.app/fields

**Comment by Veetaha** [comment]
@8398a7 nope, this is not in a matrix.
Adding GITHUB_TOKEN helped a bit, but the link still ends with `undefined`:
![image](https://user-images.githubusercontent.com/36276403/86260328-cc5fc000-bbc5-11ea-8ac1-13eaf6fc937b.png)

**Comment by 8398a7** [comment]
If it tells you a public repository, I'll investigate.

**Comment by Veetaha** [comment]
@8398a7 
Here is the run, I tested it in a public repo. The slack channel is private tho :D
https://github.com/Veetaha/sandbox-repo/runs/827436880?check_suite_focus=true

**Comment by 8398a7** [comment]
I saw it.
Can the github token be taken in the specified way as well?
`GITHUB_TOKEN: ${{ github.token }}`

The documentation states the following, can you try it here?
`GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`

**Comment by Veetaha** [comment]
Nope, this doesn't work either

**Comment by 8398a7** [comment]
I found the cause.
If you remove `name: sandbox jon`, it works.

The problem that you can't get the file when you change the name seems to be difficult to solve because of the API specification.
If I were to solve it, I'd have to tell the action-slack the name like this:

```yaml
    uses: 8398a7/action-slack@v3
    with:
      status: failure
      fields: job,author
      text: "Testing failure message to PR. Hello world!."
      author_name: ""
      override_job_name: sandbox jon
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```
